export const GET_PROPERTIES_SUCCEEDED = 'GET_PROPERTIES_SUCCEEDED';
export const GET_PROPERTIES_REQUESTED = 'GET_PROPERTIES_REQUESTED';
export const GET_PROPERTIES_FAILED = 'GET_PROPERTIES_FAILED';

export default {
  GET_PROPERTIES_REQUESTED,
  GET_PROPERTIES_SUCCEEDED,
  GET_PROPERTIES_FAILED,
};
