export const FETCH_PROPERTIES_SUCCEEDED = 'FETCH_PROPERTIES_SUCCEEDED';
export const FETCH_PROPERTIES_REQUESTED = 'FETCH_PROPERTIES_REQUESTED';
export const FETCH_PROPERTIES_FAILED = 'FETCH_PROPERTIES_FAILED';

export default {
  FETCH_PROPERTIES_REQUESTED,
  FETCH_PROPERTIES_SUCCEEDED,
  FETCH_PROPERTIES_FAILED,
};
