export const GET_ZAP_PROPERTIES_SUCCEEDED = 'GET_ZAP_PROPERTIES_SUCCEEDED';
export const GET_ZAP_PROPERTIES_FAILED = 'GET_ZAP_PROPERTIES_FAILED';

export default {
  GET_ZAP_PROPERTIES_SUCCEEDED,
  GET_ZAP_PROPERTIES_FAILED,
};
