export const FETCH_ZAP_PROPERTIES_SUCCEEDED = 'FETCH_ZAP_PROPERTIES_SUCCEEDED';
export const FETCH_ZAP_PROPERTIES_FAILED = 'FETCH_ZAP_PROPERTIES_FAILED';

export default {
  FETCH_ZAP_PROPERTIES_SUCCEEDED,
  FETCH_ZAP_PROPERTIES_FAILED,
};
