export const GET_VIVA_PROPERTIES_SUCCEEDED = 'GET_VIVA_PROPERTIES_SUCCEEDED';
export const GET_VIVA_PROPERTIES_FAILED = 'GET_VIVA_PROPERTIES_FAILED';

export default {
  GET_VIVA_PROPERTIES_SUCCEEDED,
  GET_VIVA_PROPERTIES_FAILED,
};
