export const FETCH_VIVA_PROPERTIES_SUCCEEDED =
  'FETCH_VIVA_PROPERTIES_SUCCEEDED';
export const FETCH_VIVA_PROPERTIES_FAILED = 'FETCH_VIVA_PROPERTIES_FAILED';

export default {
  FETCH_VIVA_PROPERTIES_SUCCEEDED,
  FETCH_VIVA_PROPERTIES_FAILED,
};
